apiVersion: v1
kind: PersistentVolume
metadata:
  name: boomi-storage
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=3
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: premstormck.file.core.windows.net
    path: /premstormck/boomishare01
