apiVersion: v1
kind: PersistentVolume
metadata:
  name: boomi-storage
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - vers=4
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: mystoac1.file.core.windows.net
    path: /mystoac1/boominfs01
