apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pac
  labels:
    app: pac
spec:
  selector:
    matchLabels:
      app: pac
  replicas: 2
  template:
    metadata:
      labels:
        app: pac
    spec:
      terminationGracePeriodSeconds: 900
      volumes:
        - name: boomi-storage
          persistentVolumeClaim:
            claimName: pv-volume
      nodeSelector:
        agentpool: userpool            
      securityContext:
        fsGroup: 1000
      containers:
      - image: boomi/cloud:4.2.0
        imagePullPolicy: Always
        name: atom-node
        ports:
        - containerPort: 9090
          protocol: TCP
        - containerPort: 9093
          protocol: TCP
        lifecycle:
          preStop:
            exec:
              command:
                - sh
                - /home/boomi/scaledown.sh
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 500m
            memory: 768Mi
        volumeMounts:
          - name: boomi-storage
            mountPath: "/mnt/boomi"
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /_admin/readiness
            port: 9090
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /_admin/liveness
            port: 9090
        env:
        - name: BOOMI_ATOMNAME
          value: "boomi-pac"
        - name: ATOM_LOCALHOSTID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTALL_TOKEN
          value: "cloud-24fc7eac-98c2-4f2a-9af5-b6e2a8616dfa"
        - name : BOOMI_ENVIRONMENTID
          value: "40590140-dc5b-4c49-89f9-47f99641a0d4"
        - name: CONTAINER_PROPERTIES_OVERRIDES
          value: "com.boomi.container.debug=false|com.boomi.deployment.quickstart=true"
